// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entailer.proto

package com.enxime.entail.share;

public final class EntailProto {
  private EntailProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ToServerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string filePath = 1;
    boolean hasFilePath();
    String getFilePath();
    
    // optional string command = 5;
    boolean hasCommand();
    String getCommand();
    
    // repeated string parameter = 9;
    java.util.List<String> getParameterList();
    int getParameterCount();
    String getParameter(int index);
  }
  public static final class ToServer extends
      com.google.protobuf.GeneratedMessage
      implements ToServerOrBuilder {
    // Use ToServer.newBuilder() to construct.
    private ToServer(Builder builder) {
      super(builder);
    }
    private ToServer(boolean noInit) {}
    
    private static final ToServer defaultInstance;
    public static ToServer getDefaultInstance() {
      return defaultInstance;
    }
    
    public ToServer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enxime.entail.share.EntailProto.internal_static_com_enxime_entail_share_ToServer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enxime.entail.share.EntailProto.internal_static_com_enxime_entail_share_ToServer_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string filePath = 1;
    public static final int FILEPATH_FIELD_NUMBER = 1;
    private java.lang.Object filePath_;
    public boolean hasFilePath() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          filePath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string command = 5;
    public static final int COMMAND_FIELD_NUMBER = 5;
    private java.lang.Object command_;
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCommand() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          command_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCommandBytes() {
      java.lang.Object ref = command_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        command_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string parameter = 9;
    public static final int PARAMETER_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList parameter_;
    public java.util.List<String>
        getParameterList() {
      return parameter_;
    }
    public int getParameterCount() {
      return parameter_.size();
    }
    public String getParameter(int index) {
      return parameter_.get(index);
    }
    
    private void initFields() {
      filePath_ = "";
      command_ = "";
      parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFilePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilePathBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(5, getCommandBytes());
      }
      for (int i = 0; i < parameter_.size(); i++) {
        output.writeBytes(9, parameter_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilePathBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCommandBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameter_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parameter_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParameterList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.enxime.entail.share.EntailProto.ToServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enxime.entail.share.EntailProto.ToServer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enxime.entail.share.EntailProto.ToServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enxime.entail.share.EntailProto.internal_static_com_enxime_entail_share_ToServer_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enxime.entail.share.EntailProto.internal_static_com_enxime_entail_share_ToServer_fieldAccessorTable;
      }
      
      // Construct using com.enxime.entail.share.EntailProto.ToServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        filePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enxime.entail.share.EntailProto.ToServer.getDescriptor();
      }
      
      public com.enxime.entail.share.EntailProto.ToServer getDefaultInstanceForType() {
        return com.enxime.entail.share.EntailProto.ToServer.getDefaultInstance();
      }
      
      public com.enxime.entail.share.EntailProto.ToServer build() {
        com.enxime.entail.share.EntailProto.ToServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.enxime.entail.share.EntailProto.ToServer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.enxime.entail.share.EntailProto.ToServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.enxime.entail.share.EntailProto.ToServer buildPartial() {
        com.enxime.entail.share.EntailProto.ToServer result = new com.enxime.entail.share.EntailProto.ToServer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filePath_ = filePath_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.command_ = command_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          parameter_ = new com.google.protobuf.UnmodifiableLazyStringList(
              parameter_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parameter_ = parameter_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enxime.entail.share.EntailProto.ToServer) {
          return mergeFrom((com.enxime.entail.share.EntailProto.ToServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.enxime.entail.share.EntailProto.ToServer other) {
        if (other == com.enxime.entail.share.EntailProto.ToServer.getDefaultInstance()) return this;
        if (other.hasFilePath()) {
          setFilePath(other.getFilePath());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (!other.parameter_.isEmpty()) {
          if (parameter_.isEmpty()) {
            parameter_ = other.parameter_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParameterIsMutable();
            parameter_.addAll(other.parameter_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFilePath()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filePath_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000002;
              command_ = input.readBytes();
              break;
            }
            case 74: {
              ensureParameterIsMutable();
              parameter_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string filePath = 1;
      private java.lang.Object filePath_ = "";
      public boolean hasFilePath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFilePath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
        return this;
      }
      public Builder clearFilePath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      void setFilePath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
      }
      
      // optional string command = 5;
      private java.lang.Object command_ = "";
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCommand() {
        java.lang.Object ref = command_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          command_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCommand(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        command_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = getDefaultInstance().getCommand();
        onChanged();
        return this;
      }
      void setCommand(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        command_ = value;
        onChanged();
      }
      
      // repeated string parameter = 9;
      private com.google.protobuf.LazyStringList parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParameterIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          parameter_ = new com.google.protobuf.LazyStringArrayList(parameter_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getParameterList() {
        return java.util.Collections.unmodifiableList(parameter_);
      }
      public int getParameterCount() {
        return parameter_.size();
      }
      public String getParameter(int index) {
        return parameter_.get(index);
      }
      public Builder setParameter(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterIsMutable();
        parameter_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addParameter(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParameterIsMutable();
        parameter_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllParameter(
          java.lang.Iterable<String> values) {
        ensureParameterIsMutable();
        super.addAll(values, parameter_);
        onChanged();
        return this;
      }
      public Builder clearParameter() {
        parameter_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addParameter(com.google.protobuf.ByteString value) {
        ensureParameterIsMutable();
        parameter_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.enxime.entail.share.ToServer)
    }
    
    static {
      defaultInstance = new ToServer(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.enxime.entail.share.ToServer)
  }
  
  public interface ToClientOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string filePath = 1;
    boolean hasFilePath();
    String getFilePath();
    
    // optional int32 resultCode = 5;
    boolean hasResultCode();
    int getResultCode();
    
    // optional string resultMessage = 9;
    boolean hasResultMessage();
    String getResultMessage();
    
    // repeated string tailLine = 13;
    java.util.List<String> getTailLineList();
    int getTailLineCount();
    String getTailLine(int index);
  }
  public static final class ToClient extends
      com.google.protobuf.GeneratedMessage
      implements ToClientOrBuilder {
    // Use ToClient.newBuilder() to construct.
    private ToClient(Builder builder) {
      super(builder);
    }
    private ToClient(boolean noInit) {}
    
    private static final ToClient defaultInstance;
    public static ToClient getDefaultInstance() {
      return defaultInstance;
    }
    
    public ToClient getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.enxime.entail.share.EntailProto.internal_static_com_enxime_entail_share_ToClient_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.enxime.entail.share.EntailProto.internal_static_com_enxime_entail_share_ToClient_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string filePath = 1;
    public static final int FILEPATH_FIELD_NUMBER = 1;
    private java.lang.Object filePath_;
    public boolean hasFilePath() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          filePath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 resultCode = 5;
    public static final int RESULTCODE_FIELD_NUMBER = 5;
    private int resultCode_;
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getResultCode() {
      return resultCode_;
    }
    
    // optional string resultMessage = 9;
    public static final int RESULTMESSAGE_FIELD_NUMBER = 9;
    private java.lang.Object resultMessage_;
    public boolean hasResultMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getResultMessage() {
      java.lang.Object ref = resultMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          resultMessage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResultMessageBytes() {
      java.lang.Object ref = resultMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        resultMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string tailLine = 13;
    public static final int TAILLINE_FIELD_NUMBER = 13;
    private com.google.protobuf.LazyStringList tailLine_;
    public java.util.List<String>
        getTailLineList() {
      return tailLine_;
    }
    public int getTailLineCount() {
      return tailLine_.size();
    }
    public String getTailLine(int index) {
      return tailLine_.get(index);
    }
    
    private void initFields() {
      filePath_ = "";
      resultCode_ = 0;
      resultMessage_ = "";
      tailLine_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFilePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilePathBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(5, resultCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(9, getResultMessageBytes());
      }
      for (int i = 0; i < tailLine_.size(); i++) {
        output.writeBytes(13, tailLine_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilePathBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, resultCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getResultMessageBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tailLine_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(tailLine_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTailLineList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.enxime.entail.share.EntailProto.ToClient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.enxime.entail.share.EntailProto.ToClient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.enxime.entail.share.EntailProto.ToClient prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.enxime.entail.share.EntailProto.ToClientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.enxime.entail.share.EntailProto.internal_static_com_enxime_entail_share_ToClient_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.enxime.entail.share.EntailProto.internal_static_com_enxime_entail_share_ToClient_fieldAccessorTable;
      }
      
      // Construct using com.enxime.entail.share.EntailProto.ToClient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        filePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        resultMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        tailLine_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.enxime.entail.share.EntailProto.ToClient.getDescriptor();
      }
      
      public com.enxime.entail.share.EntailProto.ToClient getDefaultInstanceForType() {
        return com.enxime.entail.share.EntailProto.ToClient.getDefaultInstance();
      }
      
      public com.enxime.entail.share.EntailProto.ToClient build() {
        com.enxime.entail.share.EntailProto.ToClient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.enxime.entail.share.EntailProto.ToClient buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.enxime.entail.share.EntailProto.ToClient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.enxime.entail.share.EntailProto.ToClient buildPartial() {
        com.enxime.entail.share.EntailProto.ToClient result = new com.enxime.entail.share.EntailProto.ToClient(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filePath_ = filePath_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resultMessage_ = resultMessage_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          tailLine_ = new com.google.protobuf.UnmodifiableLazyStringList(
              tailLine_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.tailLine_ = tailLine_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.enxime.entail.share.EntailProto.ToClient) {
          return mergeFrom((com.enxime.entail.share.EntailProto.ToClient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.enxime.entail.share.EntailProto.ToClient other) {
        if (other == com.enxime.entail.share.EntailProto.ToClient.getDefaultInstance()) return this;
        if (other.hasFilePath()) {
          setFilePath(other.getFilePath());
        }
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasResultMessage()) {
          setResultMessage(other.getResultMessage());
        }
        if (!other.tailLine_.isEmpty()) {
          if (tailLine_.isEmpty()) {
            tailLine_ = other.tailLine_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTailLineIsMutable();
            tailLine_.addAll(other.tailLine_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFilePath()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filePath_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000002;
              resultCode_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000004;
              resultMessage_ = input.readBytes();
              break;
            }
            case 106: {
              ensureTailLineIsMutable();
              tailLine_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string filePath = 1;
      private java.lang.Object filePath_ = "";
      public boolean hasFilePath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFilePath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
        return this;
      }
      public Builder clearFilePath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      void setFilePath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
      }
      
      // optional int32 resultCode = 5;
      private int resultCode_ ;
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getResultCode() {
        return resultCode_;
      }
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000002;
        resultCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultCode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string resultMessage = 9;
      private java.lang.Object resultMessage_ = "";
      public boolean hasResultMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getResultMessage() {
        java.lang.Object ref = resultMessage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          resultMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResultMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resultMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resultMessage_ = getDefaultInstance().getResultMessage();
        onChanged();
        return this;
      }
      void setResultMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        resultMessage_ = value;
        onChanged();
      }
      
      // repeated string tailLine = 13;
      private com.google.protobuf.LazyStringList tailLine_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTailLineIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          tailLine_ = new com.google.protobuf.LazyStringArrayList(tailLine_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<String>
          getTailLineList() {
        return java.util.Collections.unmodifiableList(tailLine_);
      }
      public int getTailLineCount() {
        return tailLine_.size();
      }
      public String getTailLine(int index) {
        return tailLine_.get(index);
      }
      public Builder setTailLine(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTailLineIsMutable();
        tailLine_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addTailLine(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTailLineIsMutable();
        tailLine_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllTailLine(
          java.lang.Iterable<String> values) {
        ensureTailLineIsMutable();
        super.addAll(values, tailLine_);
        onChanged();
        return this;
      }
      public Builder clearTailLine() {
        tailLine_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      void addTailLine(com.google.protobuf.ByteString value) {
        ensureTailLineIsMutable();
        tailLine_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.enxime.entail.share.ToClient)
    }
    
    static {
      defaultInstance = new ToClient(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.enxime.entail.share.ToClient)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_enxime_entail_share_ToServer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_enxime_entail_share_ToServer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_enxime_entail_share_ToClient_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_enxime_entail_share_ToClient_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016entailer.proto\022\027com.enxime.entail.shar" +
      "e\"@\n\010ToServer\022\020\n\010filePath\030\001 \002(\t\022\017\n\007comma" +
      "nd\030\005 \001(\t\022\021\n\tparameter\030\t \003(\t\"Y\n\010ToClient\022" +
      "\020\n\010filePath\030\001 \002(\t\022\022\n\nresultCode\030\005 \001(\005\022\025\n" +
      "\rresultMessage\030\t \001(\t\022\020\n\010tailLine\030\r \003(\tB&" +
      "\n\027com.enxime.entail.shareB\013EntailProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_enxime_entail_share_ToServer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_enxime_entail_share_ToServer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_enxime_entail_share_ToServer_descriptor,
              new java.lang.String[] { "FilePath", "Command", "Parameter", },
              com.enxime.entail.share.EntailProto.ToServer.class,
              com.enxime.entail.share.EntailProto.ToServer.Builder.class);
          internal_static_com_enxime_entail_share_ToClient_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_enxime_entail_share_ToClient_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_enxime_entail_share_ToClient_descriptor,
              new java.lang.String[] { "FilePath", "ResultCode", "ResultMessage", "TailLine", },
              com.enxime.entail.share.EntailProto.ToClient.class,
              com.enxime.entail.share.EntailProto.ToClient.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
